# Generated by Django 4.2.1 on 2023-06-02 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_data',
            name='token',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
