# Generated by Django 4.2.1 on 2023-06-03 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nps', '0002_user_data_token'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user_data',
        ),
    ]
