# Generated by Django 4.2.1 on 2023-06-04 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nps', '0003_delete_user_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='file_uploading_status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='nps_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=50)),
                ('review', models.TextField()),
                ('nps', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('sentiment', models.CharField(max_length=50)),
            ],
        ),
    ]
