# Generated by Django 4.2.1 on 2023-06-16 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nps', '0005_nps_data_uploading_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='upload_log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=50)),
                ('file_name', models.CharField(max_length=200)),
                ('date_time', models.DateTimeField(default='2023-06-16 14:08:24.105851+05:30')),
                ('file_size', models.CharField(max_length=20)),
            ],
        ),
    ]
