# Generated by Django 4.2.1 on 2023-06-03 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google_reviews', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='google_reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=200)),
                ('review', models.TextField()),
                ('rating', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('sentiment', models.CharField(max_length=50)),
            ],
        ),
    ]
